[package]
name = "toy-payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
crossbeam = "0.8.4"
csv = "1.3.1"
dashmap = "6.1.0"
rust_decimal = { version = "1.37.1", features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
